### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to Language::translateIfTranslationStrId() must be of the type string

### ISSUE THREAD

**Issue by benhartwich** [rmbinder/FormFiller#69]
Hi,

when we try to generate labels we get a 500 error:
`2023/04/03 18:33:54 [error] 3002824#3002824: *123885 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Language::translateIfTranslationStrId() must be of the type string, null given, called in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/HtmlForm.php on line 1104 and defined in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Language.php:467
Stack trace:
#0 /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/HtmlForm.php(1104): Language::translateIfTranslationStrId()
#1 /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/HtmlForm.php(1271): HtmlForm->addSelectBox()
#2 /var/www/verwaltung/htdocs/admidio/adm_plugins/formfiller/formfiller.php(184): HtmlForm->addSelectBoxFromSql()
#3 {main}
  thrown in /var/www/verwaltung/htdocs/admidio/adm_program/system/classes/Language.php on line 467" while reading response header from upstream, client: 185.118.244.62, server: verwaltung.astronomie.at, request: "GET /adm_plugins/formfiller/formfiller.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm-verwaltung.sock:", host: "verwaltung.astronomie.at", referrer: "https://verwaltung.astronomie.at/adm_program/modules/groups-roles/lists_show.php?mode=html&rol_ids=11&urt_ids=&show_former_members=0&date_from=2023-04-03&date_to=2023-04-03&list_uuid=18e091e6-a924-48ae-bf89-ab9097065ade"
`

Can you please tell us, what could be the problem here? We´re using admidio 4.2.4 and I think the latest version of your plugin.

**Comment by rmbinder** [comment]
This argument 1, which is passed to Language::translateIfTranslationStrId(), is actually always Lastname + Firstname, e.g. "Meier Fritz". With you, however, no string is passed for a member, but NULL. 

Do you have a member whose last name and first name are empty?

**Comment by benhartwich** [comment]
Thanks for your feedback. Yes, this could be the problem. Is there any chance to get rid of this error if some of these fields are empty? Perhaps a warning message could be a great information tool.

**Comment by rmbinder** [comment]
A warning message is not impossible but difficult to resolve because these are Admidio functions.

1. I'm writing a small plugin for my tools collection that detects if certain profile fields are empty. (but I'm currently still busy with a new plugin). A display of empty profile fields could probably also be solved with lists.
2. Take a look at the Admidio plugin statistics. There is a sample statistic called "Profilvollständigkeit".

**Comment by benhartwich** [comment]
Ok, thanks. I checked firstname und last name and corrected it, but the error still persists. are there any other fields, which could cause this problem?

**Comment by rmbinder** [comment]
The associated SQL query just reads user_id, lastname and firstname and groups by the first letter of the first name. I'll try to write something to show the values that are read out from you.
